function [] = testProgram()

% 26/11 - 15:06  - Gittad
% img=imread('pictures/Bygg_1.png');    % OK - med tre punkter
% img=imread('pictures/Bygg_1a.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_1b.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_1c.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_1d.png');   % N?stanm- med tre punkter
% img=imread('pictures/Bygg_1e.png');   % Nope - f?rvr?ngd, 4punkter?
% img=imread('pictures/Bygg_2.png');    % OK - med tre punkter
% img=imread('pictures/Bygg_2a.png');   % V?ldigt n?ra
% img=imread('pictures/Bygg_2b.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_2c.png');   % OK- med tre punkter
% img=imread('pictures/Bygg_2d.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_2e.png');   % Nope - f?rvr?ngd, 4punkter?
% img=imread('pictures/Bygg_3.png');    % OK - med tre punkter
% img=imread('pictures/Bygg_3_Illum.png'); 
% img=imread('pictures/Bygg_3a.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_3b.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_3c.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_3d.png');   % OK - med tre punkter
% img=imread('pictures/Bygg_3e.png');   % Nope - Flyttas ur bild
% img=imread('pictures/Hus_1.png');     % Bra ib?rjan, en till punkt
% img=imread('pictures/Hus_1_Illum.png'); 
% img=imread('pictures/Hus_1a.png'); 
% img=imread('pictures/Hus_1b.png'); 
% img=imread('pictures/Hus_1c.png'); 
% img=imread('pictures/Hus_1d.png'); 
% img=imread('pictures/Hus_1e.png'); 
% img=imread('pictures/Hus_2.png'); 
% img=imread('pictures/Hus_2a.png'); 
% img=imread('pictures/Hus_2b.png'); 
% img=imread('pictures/Hus_2c.png'); 
% img=imread('pictures/Hus_2d.png'); 
% img=imread('pictures/Hus_2e.png'); 
% img=imread('pictures/Hus_3.png'); 
% img=imread('pictures/Hus_3a.png'); 
% img=imread('pictures/Hus_3b.png'); 
% img=imread('pictures/Hus_3b.png'); 
% img=imread('pictures/Hus_3c.png'); 
% img=imread('pictures/Hus_3d.png'); 
% img=imread('pictures/Hus_3e.png'); 
% img=imread('pictures/Hus_4.png'); 
% img=imread('pictures/Hus_4_Illum.png'); 
% img=imread('pictures/Hus_4a.png'); 
% img=imread('pictures/Hus_4b.png'); 
% img=imread('pictures/Hus_4c.png'); 
% img=imread('pictures/Hus_4d.png'); 
% img=imread('pictures/Hus_4e.png'); 
% img=imread('pictures/Husannons_full.png'); 
% img=imread('pictures/Husannons_full_Illum.png'); 
tnm034(img);

